[build]
  command = "npm install && node build-for-netlify.js && cd client && npx vite build --outDir ../dist/public"
  publish = "dist/public"
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200