services:
  - type: web
    name: trading-journal
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: trading-journal-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: trading-journal-db
    databaseName: trading_journal
    user: trading_journal_user
    plan: free