services:
  - type: web
    name: trading-journal
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: trading-journal-db
          property: connectionString

databases:
  - name: trading-journal-db
    databaseName: trading_journal
    user: trading_journal_user
    plan: free