services:
  - type: web
    name: trading-journal
    env: node
    repo: https://github.com/Haze844/TradingJournall.git
    buildCommand: npm install && npm run build
    startCommand: node setup-db.js && node render-patch.cjs && node dist/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false  # Stelle sicher, dass du diesen Schlüssel im Render Dashboard einrichtest!