services:
  - type: web
    name: trading-journal
    env: node
    repo: https://github.com/Haze844/TradingJournall.git
    buildCommand: npm install --include=dev && npm run build
    startCommand: node server/standalone-express.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: SESSION_SECRET
        generateValue: true
    
# Verbindung zur Neon Postgres-Datenbank erfolgt über die Render Dashboard-Einstellung
# DATABASE_URL muss im Dashboard konfiguriert werden!